name: Daily Run of automate.py

on:
  push:
    branches:
      - main
  schedule:
    # Runs the workflow daily at 12:00 AM UTC
    - cron: '0 0 * * *'

jobs:
  Run-Python-Script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python 3.14.0-alpha.2
        uses: actions/setup-python@v4
        with:
          python-version: 3.14.0-alpha.2

      # Step 3: Install system dependencies for Pillow
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev python3-setuptools libtiff5-dev libjpeg8-dev libopenjp2-7-dev zlib1g-dev \
              libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python3-tk \
              libharfbuzz-dev libfribidi-dev libxcb1-dev

      # Step 4: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade Pillow
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 5: Run the Python script
      - name: Run automate.py
        run: python automate.py

      # Step 6: Commit and push changes
      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add .
          git commit -m "Automated update: processed and updated files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 7: Post-run status
      - run: echo "🍏 The script execution completed with status ${{ job.status }}."